<?php
/* 
 * Generated by CRUDigniter v3.4 
 * www.crudigniter.com
 */
 
class Employee_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get employee by id
     */
    function get_employee($id)
    {
        return $this->db->get_where('employee',array('id'=>$id))->row();
    }
    
    /*
     * Get all employees count
     */
    function get_all_employees_count()
    {
        $this->db->from('employee');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all employees
     */
    function get_all_employees($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('employee')->result();
    }

    function employee_search($limit,$start,$search)
    {
        $this->db->like('id',$search)
                ->or_like('first_name',$search)
                ->or_like('last_name',$search);
        if($limit > -1) {
            $this->db->limit($limit,$start);
        }
        $query = $this->db->get('employee');
       
        if($query->num_rows()>0)
        {
            return $query->result();  
        }
        else
        {
            return null;
        }
    }

    function employee_search_count($search)
    {
        $query = $this->db->like('id',$search)
                ->or_like('first_name',$search)
                ->or_like('last_name',$search)
                ->get('employee');
    
        return $query->num_rows();
    }
        
    /*
     * function to add new employee
     */
    function add_employee($params)
    {
        $this->db->insert('employee',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update employee
     */
    function update_employee($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('employee',$params);
    }
    
    /*
     * function to delete employee
     */
    function delete_employee($id)
    {
        return $this->db->delete('employee',array('id'=>$id));
    }
}
